### ISSUE TITLE
BILLING_RESPONSE_RESULT_SERVICE_UNAVAILABLE

### ISSUE THREAD

**Issue by Sofianio** [appcelerator-modules/ti.inappbilling#11]
Hi,
I'm having a pb running the example, the returnCode from `purchase` method is `2` with a pop-up message `Authentication is required` which is not included in the Constants, I searched & found that it's BILLING_RESPONSE_RESULT_SERVICE_UNAVAILABLE (was missing even in IAB docs).
What can i do to fix this (i did all the requested steps).
Thank you in advance.

**Comment by nuno** [comment]
@Sofianio Can you give us the motive why you close it? can you share the issue for the others know? Thanks!

**Comment by Sofianio** [comment]
The problem was a miss-configuration Google play developer console (don't remember exactly what was missing), not in the module.
