### ISSUE TITLE
Fails on Nexus 5 with Android 6.0

### ISSUE THREAD

**Issue by annakozy2011** [appcelerator-modules/ti.inappbilling#14]
On the device in Subj, el app fails without starting with this error (on Genymotion with same params, it works). So far the % of devices with 6.0 is small, but for the future:  

01-08 07:08:01.077: E/AndroidRuntime(23388): FATAL EXCEPTION: KrollRuntimeThread
01-08 07:08:01.077: E/AndroidRuntime(23388): Process: com.womala.womalaandroid, PID: 23388
01-08 07:08:01.077: E/AndroidRuntime(23388): java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/com.womala.womalaandroid-2/lib/arm/libti.inappbilling.so: has text relocations
01-08 07:08:01.077: E/AndroidRuntime(23388): 	at java.lang.Runtime.loadLibrary(Runtime.java:372)
01-08 07:08:01.077: E/AndroidRuntime(23388): 	at java.lang.System.loadLibrary(System.java:1076)
01-08 07:08:01.077: E/AndroidRuntime(23388): 	at org.appcelerator.kroll.runtime.v8.V8Runtime.loadExternalModules(V8Runtime.java:132)
01-08 07:08:01.077: E/AndroidRuntime(23388): 	at org.appcelerator.kroll.runtime.v8.V8Runtime.initRuntime(V8Runtime.java:99)
01-08 07:08:01.077: E/AndroidRuntime(23388): 	at org.appcelerator.kroll.KrollRuntime.doInit(KrollRuntime.java:185)
01-08 07:08:01.077: E/AndroidRuntime(23388): 	at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:109)
01-08 07:08:01.078: W/ActivityManager(777):   Force finishing activity com.womala.womalaandroid/.BwomActivity

**Comment by ashcoding** [comment]
Which version of the module are you using?

Is it https://github.com/appcelerator-modules/ti.inappbilling/releases/tag/v3.0.2 ?

**Comment by annakozy2011** [comment]
Yes, freshly downloaded a couple of days ago and recompiled.

**Comment by annakozy2011** [comment]
I am still trying, seems to be this issue:

http://stackoverflow.com/questions/32346402/libavcodec-so-has-text-relocations

**Comment by annakozy2011** [comment]
I indeed had Titanium 5.1.1 and Target Sdk set to 23

**Comment by annakozy2011** [comment]
I will reply in 3-4 hours, i m outside

**Comment by ashcoding** [comment]
Thanks for the update.

**Comment by annakozy2011** [comment]
Update. 

It is indeed what was in the stackoverflow. If I downgrade Titanium to 5.0.2 and Target SDK to 22, it works on Android 6.0

Yes, I am working with v3.0.2, I just checked the manifest. I downloaded the zip and recomplied everything on monday.

**Comment by annakozy2011** [comment]
I have done one last test, 

Titanium SKD 5.1.1

in manifest: 

android:targetSdkVersion="23"

I have used the pre-built module I have downloaded right now from here (to exclude any problem with my environment): 
https://github.com/appcelerator-modules/ti.inappbilling/releases/tag/v3.0.2 

Result: CRASH on Nexus 5, Android 6.0 (device)

I guess here I am compiling with target SDK 22 (that does not crash on this problem), and the problem becomes yours :)

**Comment by ashcoding** [comment]
@annakozy2011 thanks for the update. Will need to investigate this.

**Comment by ashcoding** [comment]
Created a ticket to address this issue. https://jira.appcelerator.org/browse/MOD-2188

**Comment by annakozy2011** [comment]
Thanks

**Comment by annakozy2011** [comment]
Any progress? I cannot compile on newer SDKs of Titanium, because all sdks after 5.0.2 request android:targetSdkVersion="23".... and it crashes on 6.0 that way.

**Comment by ashcoding** [comment]
@annakozy2011 with v3.0.2, I'm unable to reproduce the crash. Are there other details/logs you can provide?

**Comment by annakozy2011** [comment]
Did you try on device?  It only crashes on device, weirdly, on genymotion i
dont get it to crash either

Yes, i have the logs for the crash.... Maybe i should make a test app to
exclude other reasons...

**Comment by annakozy2011** [comment]
Close this bug, version 3.0.2 is fine (version 3.0.1 is not). I first got the log from a friend who obviously tried with the old version (that used 3.0.1), and later it kept crashing, but other libraries were responsible.

**Comment by deckameron** [comment]
Hi @annakozy2011,

I have been trying to use 3.0.2 on my Nexus 5 with Android 6.0.1 and it just won't work with Titanium SDK 5.2.1. I can't go back to SDK 5.0.2 because I have already made a lot of changes using cards and my client have already approved it. How did you manage to solve it?

[ERROR] :  linker: /data/app/com.douglas.upflix-1/lib/arm/libmetal.admobgoogleplay.so: has text relocations

**Comment by ashcoding** [comment]
@deckameron That looks like a different bug/module causing your issues. It mentions admobgoogleplay in error log you included. What modules are you including? AdMob?

**Comment by spudz000** [comment]
So what is the resolution for this?  I've just updated my app to 5.2.2.GA and compiled for SDK 23, now I'm seeing crashing with Android 6:

java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/com.XXX.XXX/lib/arm/libti.inappbilling.so: has text relocations
	at java.lang.Runtime.loadLibrary(Runtime.java:372)
	at java.lang.System.loadLibrary(System.java:1076)
	at org.appcelerator.kroll.runtime.v8.V8Runtime.loadExternalModules(V8Runtime.java:132)
	at org.appcelerator.kroll.runtime.v8.V8Runtime.initRuntime(V8Runtime.java:99)
	at org.appcelerator.kroll.KrollRuntime.doInit(KrollRuntime.java:205)
	at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:114)

**Comment by ashcoding** [comment]
@spudz000 which version of inappbilling module are you using?

**Comment by spudz000** [comment]
I am using 3.0.0 from the Appcelerator store:
https://marketplace.appcelerator.com/apps/776#!overview

Is there a released 3.0.2 someplace I should be using instead of the store?

**Comment by Geek-Fish** [comment]
@spudz000 Use gitTio http://gitt.io/component/ti.inappbilling - It makes your life so much easier :) You can install/update modules right inside Studio. 3.0.2 is available.

**Comment by ashcoding** [comment]
@spudz000 I was going to recommend v3.0.2 from here. https://github.com/appcelerator-modules/ti.inappbilling/releases

**Comment by spudz000** [comment]
Thank you all.  I don't have an android 6 device so I can't really test this but I'm going to have to give it a shot.

Why isn't this the current release through the appcelerator store.

**Comment by Geek-Fish** [comment]
I have an LG G4 running Android 6 and 3.0.2 is working fine for me - I can
purchase and restore purchases just fine.

Not sure why it's not in the store. IMO, the store doesn't seem to be
updated often. I always use Github or GitTio for modules.
